### ISSUE TITLE
"content" folders are not published if they don't contain at least one file

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1396]
If I specify a `content` folder in `project.json` that doesn't contain any files ...
```json
"content": [ 
    "Views", 
    "wwwroot",
    "logs"
],
```
(`logs` in this case is an empty folder) ... the published output doesn't include the folder ...

![capture1](https://cloud.githubusercontent.com/assets/1622880/13025622/f08ca554-d1c0-11e5-993c-911715d765e2.PNG)

If I put a file in the `logs` folder (`test.txt` in this case), it publishes the folder ...

![capture2](https://cloud.githubusercontent.com/assets/1622880/13025656/c6c64ae4-d1c1-11e5-86ef-31e453cb3bc9.PNG)

I don't think it should work that way. If I specify an empty `content` folder (or a series of nested empty folders), then I should get folders in the published output that match what I'm requesting.

**Comment by ArieJones** [comment]
Is this actually because this is the "legacy" way that it was handled in ASP.NET?  This has always been an issue and the Visual Studio Team never provided a solution to it , other than placing a dummy file into the directory. 

With that said, I think that @GuardRex makes a valid point in that if we go through the trouble of specifying a content folder in the project.json file then it should honor that on publishing.

**Comment by blackdwarf** [comment]
@davidfowl @piotrpMSFT this seems like a reasonable expectation to me, actually. Thoughts?

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

**Comment by GuardRex** [comment]
In case anyone stumbles in here looking for the "how-to" on creating the `Logs` folder (or any other content folder for that matter) with MSBuild and `csproj`, do this ...

In the `<ItemGroup>`, where you have your `<Compile ... />` and `<EmbeddedResource ... />` entries, add ...
```
<Content Include="Logs\*" Exclude="Logs\*.log">
  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
</Content>
```
... I have an `Exclude` attribute on there to keep any log files that were produced as a result of Debug runs out of the published output ... no point in sending any of those to the server.

That will work as long as the `Logs` folder has a file in it. To catch the case where the folder doesn't have any files in it (I mean unless you really like having a `dummy.txt` file in your project :smile: ), place this at the end of the `csproj` file ...
```
<Target Name="AfterPublish">
  <MakeDir Directories="$(PublishDir)Logs" Condition="!Exists('$(PublishDir)Logs')" />
</Target>
```
... just inside the closing `</Project>` tag. It must come **after** the `Import` for the `Microsoft.CSharp.targets` entry.

**Comment by GuardRex** [comment]
@piotrpMSFT The approach described above to create a `Logs` folder in published output  ...
```xml
<Target Name="AfterPublish">
  <MakeDir Directories="$(PublishDir)Logs" Condition="!Exists('$(PublishDir)Logs')" />
</Target>
```
... has broken with the latest MSBuild updates. When ...
```xml
<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
```
... went away, it stopped working. I'm back to needing a way to create an empty `Logs` folder in the published output.

I can go back to a `dummy.txt` file in the `Logs` folder with ...
```xml
<ItemGroup>
  <Content Include="Logs\**">
    <CopyToPublishDirectory>Always</CopyToPublishDirectory>
  </Content>
</ItemGroup>
```
... but *eeeeee-yuck!* :smile:

Do you know how to get `AfterPublish` working again?

The test project looks like this ...

`csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyTitle>Test Self-contained Application</AssemblyTitle>
    <TargetFramework>netcoreapp1.2</TargetFramework>
    <WarningsAsErrors>true</WarningsAsErrors>
    <DebugType>Portable</DebugType>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>testselfcontained</AssemblyName>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NETSTandard.Library" Version="1.6.1" />
    <PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR" Version="1.1.0" />
    <PackageReference Include="Microsoft.NETCore.DotNetHostPolicy" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.2.0-*" />
  </ItemGroup>

  <Target Name="AfterPublish">
    <MakeDir Directories="$(PublishDir)Logs" Condition="!Exists('$(PublishDir)Logs')" />
  </Target>

</Project>
```
Environment:
```
.NET Command Line Tools (1.0.0-preview5-004275)

Product Information:
 Version:            1.0.0-preview5-004275
 Commit SHA-1 hash:  f1c16e59d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004275
```

**Comment by pksorensen** [comment]
I just ran into the same problem with todays dotnet core tooling. Any folder not created prior to dotnet publish call will not be published. My case is that I have prepublish tasks running that generate some files, but these files are not published due to the folders did not exists prior to calling dotnet publish.

**Comment by GuardRex** [comment]
@pksorensen Not sure if this will help in your case, but I needed an empty folder, and `Content Include` would only help me when there was a dummy file present in the folder, so I started using this ...
```xml
<Target Name="CreateLogsFolder" AfterTargets="AfterPublish">
  <MakeDir Directories="$(PublishDir)Logs" Condition="!Exists('$(PublishDir)Logs')" />
</Target>
```
... so perhaps a `Copy` command in there instead of a `MakeDir` would work for you?

**Comment by pksorensen** [comment]
i solved it by adding mkdir commands in my build pipeline. just expected the tooling to include those files generated in prepublish steps.

**Comment by blackdwarf** [comment]
@pksorensen can you share your project? Or a simple repro somewhere?

/cc @nguerrera @srivatsn

**Comment by pksorensen** [comment]
here is a repro: https://github.com/pksorensen/dotnet-cli-publish-repro and you can run dotnet publish -o c:\test\out to see that it do not publish a artifacts folder, even though the prepublish scripts generate the folder.

**Comment by blackdwarf** [comment]
@pksorensen ah, I see you are using project.json tooling. This issue has been fixed in the MSBuild-based tooling (just verified, it works).

**Comment by pksorensen** [comment]
@blackdwarf I am now on 2017 RC and this is still an issue.

Any files created in the targets below that didnt exists before, will not be published.

```
 <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="npm run tsc" />
    <Exec Command="grunt packLib" />
  </Target>
```
or 
```
 <Target Name="MyPrePublishTarget" BeforeTargets="Publish">
    <Exec Command="npm run tsc" />
    <Exec Command="grunt packLib" />
```

will not be published

with the following condent include.
```
<Content Include="wwwroot\**" />
```

**Comment by dasMulli** [comment]
@pksorensen this is a known issue (the globs are evaluated before the `PrepareForPublish` target runs): https://github.com/aspnet/websdk/issues/114
There is a workaround described in https://github.com/aspnet/websdk/issues/114#issuecomment-280076533
