### ISSUE TITLE
ProjectDependenciesCommand should execute in the output directory on Desktop

### ISSUE THREAD

**Issue by bricelam** [dotnet/cli#2126]
I am implementing a "dependency" type tool (as described in #2020), and using `ProjectDependenciesCommandFactory` to dispatch to the tool on `net451`. However, when I execute, the command, it tries to execute from `%USERPROFILE%\.nuget\packages\dotnet-sample\1.0.0\lib\net451`. Because of this, the CLR can't resolve any of the tool's dependencies, and I get the following exception.

    System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.Cli.Utils,
    Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
    The system cannot find the file specified.
       at SampleProjectTool.Program.Main(String[] args)

The expected behavior would be to execute the command from `bin\Debug\net451\win7-x64` where `dotnet restore` would have resolved the tools dependencies alongside the app's, and `dotnet build` would have co-located them next to the tool so the assembly loader can find them.

For reference, my code is in [bricelam/SampleProjectTool](https://github.com/bricelam/SampleProjectTool).

cc @DamianEdwards @davidfowl @Eilon @muratg @piotrpMSFT

**Comment by brthor** [comment]
I believe @piotrpMSFT ran into this and found a solution.

Check out this test here:
https://github.com/dotnet/cli/blob/rel/1.0.0/test/dotnet.Tests/PackagedCommandTests.cs#L49

**Comment by piotrpMSFT** [comment]
I'm working on a fix. we run the right exe from the wrong directory.

**Comment by Eilon** [comment]
@piotrpMSFT do you have an update on this issue? This is critical for RC2 tooling.

**Comment by Sridhar-MS** [comment]
I am picking up this now..

**Comment by brthor** [comment]
I think the right fix here is to create a new command resolver which specifically works for desktop projects only. Instead of resolving out of the package cache it would take as inputs the base path and configuration for the build invocation, pass these to the output calculator, and look for the command there.

Let's call it `DesktopOutputDirectoryCommandResolver`?

Then modify the existing `ProjectDependenciesCommandResolver` to return null for Desktop apps.

An implication of this (which I believe was discussed in a separate issue), is that the calling app must have the base path, and configuration information for the project which has the command under dependencies. the `DesktopOutputDirectoryCommandResolver` should take these as input.

@piotrpMSFT I think we talked about using a similar approach to this at some point. Thought @Sridhar-MS ?

**Comment by krwq** [comment]
Resolved by #2297

**Comment by NTaylorMullen** [comment]
This is still happening. I'm testing it in my [branch](https://github.com/aspnet/RazorTooling/tree/nimullen/net45support.55) where i'm adding net45 support to the Razor tool.

I debugged through it a bit and added [the isDesktop check](https://github.com/dotnet/cli/pull/2297/files#diff-c0cf2a403567444f15ee5a156ff5c4d9R95) and [OperatingSystemPlatform check](https://github.com/dotnet/cli/pull/2297/files#diff-c0cf2a403567444f15ee5a156ff5c4d9R98) condition into the watch window at the point [where we create the factory for the tool](https://github.com/aspnet/RazorTooling/commit/22fccd5a44d3bdc3f977ceedb656368c2b7290ba#diff-3cbae9b41162062afa688b7d2a717bd9R131) and they both evaluated to `true`.

However, it looks to still be invoking the exe in the .nuget folder instead of the users output folder:
```
C:\Users\nimullen\Documents\GitHub\Mvc\samples\TagHelperSample.Web [dev +14 ~2 -0 !]> dotnet -v razor-tooling resolve-taghelpers C:\Users\nimullen\Documents\GitHub\Mvc\samples\TagHelperSample.Web\project.json Microsoft.AspNet.Mvc.TagHelpers

Running C:\Users\nimullen\AppData\Local\Microsoft\dotnet\dotnet.exe exec --depsfile C:\Users\nimullen\.nuget\packages\.tools\dotnet-razor-tooling\1.0.0\netstandardapp1.5\dotnet-razor-tooling.deps.json --additionalprobingpath C:\Users\nimullen\.nuget\packages C:\Users\nimullen\.nuget\packages\dotnet-razor-tooling\1.0.0\lib\netstandard1.5\dotnet-razor-tooling.dll resolve-taghelpers C:\Users\nimullen\Documents\GitHub\Mvc\samples\TagHelperSample.Web\project.json Microsoft.AspNet.Mvc.TagHelpers
Process ID: 2216
Provided arguments: resolve-taghelpers C:\Users\nimullen\Documents\GitHub\Mvc\samples\TagHelperSample.Web\project.json Microsoft.AspNet.Mvc.TagHelpers
Running C:\Users\nimullen\AppData\Local\Microsoft\dotnet\dotnet.exe build C:\Users\nimullen\Documents\GitHub\Mvc\samples\TagHelperSample.Web\project.json --framework net451
Process ID: 10376
Project Microsoft.AspNetCore.Mvc.Abstractions (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc.Core (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc.ApiExplorer (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc.Cors (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc.DataAnnotations (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc.Formatters.Json (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc.Razor.Host (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc.ViewFeatures (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc.Razor (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc.Localization (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc.TagHelpers (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Mvc (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project TagHelperSample.Web (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Running C:\Users\nimullen\.nuget\packages\dotnet-razor-tooling\1.0.0\lib\net451\dotnet-razor-tooling.exe Microsoft.AspNet.Mvc.TagHelpers --assembly TagHelperSample.Web
Process ID: 13968
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.AspNetCore.Tooling.Razor.Program.Main(String[] args)
```

I pulled the latest dotnet as of an hr ago:
```
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by natemcmaster** [comment]
@NTaylorMullen which version of the package "Microsoft.DotNet.Cli.Utils" are you using?

**Comment by brthor** [comment]
@Sridhar-MS did you check in the fix for this?

**Comment by Sridhar-MS** [comment]
@NTaylorMullen which version of "Microsoft.DotNet.Cli.Utils" is being referenced?

**Comment by NTaylorMullen** [comment]
Targeting `*`, so whatever version is on our asp.net feed: `1.0.0-beta-002279`

**Comment by Sridhar-MS** [comment]
The fix went into `1.0.0-beta-002294`. The feed is https://dotnet.myget.org/feed/dotnet-cli/package/nuget/Microsoft.DotNet.Cli.Utils

Can you give it a try?

**Comment by NTaylorMullen** [comment]
Manually added the cli feed and coreclr feed and this works. Thanks @Sridhar-MS, sorry for the false alarm. Looks like we haven't pulled latest external packages recently enough.
