### ISSUE TITLE
Ubuntu 14.04 install directions are broken

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/cli#3621]
## Steps to reproduce

Install by downloading 3 .deb packages as described here: https://github.com/dotnet/cli. Run

```
sudo dpkg -i <pkg.deb>
```

for each.

Error:
```
Unpacking dotnet-sharedframework-microsoft.netcore.app-1.0.0 (1.0.0-1) ...
dpkg: dependency problems prevent configuration of dotnet-sharedframework-microsoft.netcore.app-1.0.0:
 dotnet-sharedframework-microsoft.netcore.app-1.0.0 depends on dotnet-hostfxr-1.0.1; however:
  Package dotnet-hostfxr-1.0.1 is not installed.
```

So where are the instructions on how to download the hostfxr package?

## Environment data
`dotnet --info` output:

**Comment by BruceForstall** [comment]
@schellap @gkhanna79

**Comment by schellap** [comment]
Fixed by #3622

**Comment by BruceForstall** [comment]
@schellap you only fixed the 1.0.0-preview2 branch. What about master? It's still broken, right?

**Comment by schellap** [comment]
There is usually a mop-up RI between these branches... rel/1.0.0 has become the current home page branch, so fixed it there with https://github.com/dotnet/cli/pull/3654. @blackdwarf, please port to any other branches as necessary.

**Comment by BruceForstall** [comment]
When you visit https://github.com/dotnet/cli, the fix isn't there.
