### ISSUE TITLE
F# vanilla project not compiling because of wrong version of Microsoft.NETCore.App on MacOS X

### ISSUE THREAD

**Issue by jpeinelt** [dotnet/cli#3705]
## Steps to reproduce
Create new project with `dotnet new --lang f#`
Restore project with `dotnet restore`
Run project with `dotnet run`

## Expected  behavior
The project should build, run and output "Hello World"

## Actual behavior
`run` fails the compilation after a lot of downgrade warning with the message:
    Project fsharp_test (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
    Compiling fsharp_test for .NETCoreApp,Version=v1.0
    The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc3-004459-00' was not found.
    - Check application dependencies and target a framework version installed at:
    /usr/local/share/dotnet/shared/Microsoft.NETCore.App
    - The following versions are installed: 1.0.0
    - Alternatively, install the framework version '1.0.0-rc3-004459-00'.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by Korbin73** [comment]
I'm also getting the same error. Here is the verbose output of the error:

Telemetry is: Enabled
Project core_test (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
	/Users/Lee1/Documents/core_test/bin/Debug/netcoreapp1.0/core_test.dll
	/Users/Lee1/Documents/core_test/bin/Debug/netcoreapp1.0/core_test.pdb
	/Users/Lee1/Documents/core_test/bin/Debug/netcoreapp1.0/core_test.deps.json
	/Users/Lee1/Documents/core_test/bin/Debug/netcoreapp1.0/core_test.runtimeconfig.json
Compiling core_test for .NETCoreApp,Version=v1.0
Running /usr/local/share/dotnet/dotnet compile-fsc @/Users/Lee1/Documents/core_test/obj/Debug/netcoreapp1.0/dotnet-compile.rsp
Process ID: 58814
Running /usr/local/share/dotnet/dotnet exec --depsfile /Users/Lee1/.nuget/packages/.tools/dotnet-compile-fsc/1.0.0-preview2-003071/netcoreapp1.0/dotnet-compile-fsc.deps.json --additionalprobingpath /Users/Lee1/.nuget/packages /Users/Lee1/.nuget/packages/dotnet-compile-fsc/1.0.0-preview2-003071/lib/netcoreapp1.0/dotnet-compile-fsc.dll @/Users/Lee1/Documents/core_test/obj/Debug/netcoreapp1.0/dotnet-compile.rsp
Process ID: 58815
The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc3-004459-00' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
  - Alternatively, install the framework version '1.0.0-rc3-004459-00'.
/usr/local/share/dotnet/dotnet compile-fsc @/Users/Lee1/Documents/core_test/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 131

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.4392465

**Comment by cartermp** [comment]
Thanks for the report.  This is being addressed in two places:

* F# packages for .NET Core support are being updated: https://github.com/Microsoft/visualfsharp/pull/1290
* #3627 for updated `dotnet new` templates

Documentation is also being updated:

* Issue here: https://github.com/dotnet/core-docs/issues/681
* Known Issues document: https://github.com/dotnet/core/blob/master/cli/known-issues.md

**Comment by enricosada** [comment]
**not ready yet**, but `preview2` lib/console templates can be found in https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview2

**Comment by forki** [comment]
is there an ETA?

**Comment by cartermp** [comment]
@forki Soon!  We're testing a solution right now.

**Comment by cartermp** [comment]
This should be fixed now.  Documentation for updating the output of `dotnet new -l F#` is here: https://docs.microsoft.com/en-us/dotnet/articles/fsharp/getting-started-netcore

Eventually that doc will be a lot smaller when we ship an update of the .NET Core SDK with `dotnet new` changes.

**Comment by ckuhn203** [comment]
@cartermp that link is dead and I'm still seeing this issue.

**Comment by cartermp** [comment]
@ckuhn203 Could you clarify the issue you're seeing?  Preview2 works on my mac after following [these install instructions](https://www.microsoft.com/net/core#macos):

<img width="723" alt="screen shot 2017-01-21 at 9 33 44 am" src="https://cloud.githubusercontent.com/assets/6309070/22176339/bf5f8e82-dfbc-11e6-91a5-1d29bc3873fa.png">

**Comment by forki** [comment]
Current version is 1.0.0-rc4-004597. Preview2 is ancient and still uses
project.json.

Am 21.01.2017 18:34 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by cartermp** [comment]
@forki Preview2 is still what's downloaded on the site, and that's what the issue is about.

**Comment by ckuhn203** [comment]
I originally installed the current release. Downloading & installing the LTS solved the problem.

**Comment by cartermp** [comment]
@ckuhn203 This is likely a point-in-time issue, then.  The F# SDK for the Current release is still solidifying (F# is still alpha for .NET Core).  It will be ready for both release trains soon.

**Comment by enricosada** [comment]
Ref Wiki https://github.com/dotnet/netcorecli-fsc/wiki

Use:

- preciew2 (LTS) for project.json based
- preview4 for msbuild based

I really suggest to use LTS, becuase all docs atm are about that. And can run .NET 1.1 too with a simple workaround 


Project.json based 

- preview2 (named LTS, so .NET 1.0) works
- preview2.1 (names CuRRENT, so .NET 1.1) works with workaround, see wiki


Msbuild based
- preview3/4 (.NET 1.0) works

**Comment by forki** [comment]
@enricosada they now have rc4 - we should really focus on that and just
give up that project.json stuff.

Am 21.01.2017 19:17 schrieb "Enrico Sada" <notifications@github.com>:

**Comment by enricosada** [comment]
@forki i am really really focusing on msbuild based, finishing the WIP PR in vf# to finalize msbuild based f# with sdk. 

But ihmo there are really good reason to use preview2 (LTS,xproj/project.json) not only for f# but for c# too. 

- better documentation and info online
- it's stable (mabuild change a bit project sintax between releases)
- all netcore tooling in ecosystem already works (nunit doesnt work with dotnet test in with preview4 but works preview2)
- third party use that (like aws lambda)
- it's easy to convert project.json -> msbuild when needed. 

If you already know/use dotnet core sdk, directly go msbuild based has some advantages for sure. But is not for new users Ihmo because is too bleeding edge

**Comment by maestrow** [comment]
Since having read this branch for me wasn't obvious how to solve the problem described here, so I'll leave this comment here. I'm using Windows and I have installed .NET Core SDK **1.1** from [this title page](https://www.microsoft.com/net/core#windowscmd) as was offered. Then I ran `dotnet new --lang f#`, `dotnet restore` and finaly `dotnet build`. Last command returns an error ouput:

```
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
```

This problem is solved by installing .NET Core SDK **LTS** (for now it is 1.0.3) from [here](https://www.microsoft.com/net/download/core)

**Comment by enricosada** [comment]
@maestrow you can also use preview2.1 with a workaround.

See https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-preview2.1#dotnet-new for more info
