### ISSUE TITLE
dotnet pack aborts with project.json with globbing in files/mappings

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/cli#3827]
## Steps to reproduce

project.json:

``` json
    "files": {
      "mappings": {
        "/": [ "../../*.md", "../../beanio-logo.png", "../../LICENSE" ],
        "src/Xsd": "Xsd/**/*.xsd"
      }
    }
```

Now create a package with `dotnet pack`
## Expected  behavior

Package should be created with:

```
Producing nuget package "BeanIO.4.0.0-alpha-01" for BeanIO
BeanIO -> C:\***\Source\Repos\beanio-net\src\BeanIO\bin\Debug\BeanIO.4.0.0-alpha-01.nupkg
Producing nuget package "BeanIO.4.0.0-alpha-01.symbols" for BeanIO
BeanIO -> C:\***\Source\Repos\beanio-net\src\BeanIO\bin\Debug\BeanIO.4.0.0-alpha-01.symbols.nupkg
```
## Actual behavior

Package isn't created. Message is:

```
Producing nuget package "BeanIO.4.0.0-alpha-01" for BeanIO
```

After this, the pack process gets aborted (without error message).
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

It also fails with the latest build (1.0.0-preview3-003180, SHA: d4193cd5c1)

**Comment by blackdwarf** [comment]
@fubar-coder can you provide a repo somewhere with a small repro of this? I would like to verify that it has been fixed in the Preview3+ tooling. Thanks!

**Comment by piotrpMSFT** [comment]
Moving this validation tracking issue to backlog. If we find there is still a problem here then let's move it to another milestone.
