### ISSUE TITLE
Fix help usage for dotnet pack and restore

### ISSUE THREAD

**Issue by mishra14** [dotnet/cli#4813]
Discovered this while working on similar bug in dotnet nuget command.

The help usage part of dotnet pack and dotnet restore should correctly display usage as `dotnet pack ...` or `dotnet restore ...`

1. 
```
PS C:\Users\anmishr\Documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1> dotnet restore --help
restore

Usage: restore [arguments] [options] [[--] <arg>...]]
```

2.
```
PS C:\Users\anmishr\Documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1> dotnet pack --help
pack

Usage: pack [arguments] [options] [[--] <arg>...]]
```

**Comment by piotrpMSFT** [comment]
@rrelyea thoughts?

**Comment by svick** [comment]
There's a similar issue with `dotnet msbuild`:

```
>dotnet msbuild -?
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Syntax:              MSBuild.exe [options] [project file]

[…]
Examples:

        MSBuild MyApp.sln /t:Rebuild /p:Configuration=Release
        MSBuild MyApp.csproj /t:Clean
                             /p:Configuration=Debug;TargetFrameworkVersion=v3.5
```

**Comment by blackdwarf** [comment]
The root issue has been resolved and the RC3 bits are not showing the behavior. Closing.

**Comment by mishra14** [comment]
@blackdwarf and @piotrpMSFT: 

I downloaded latest binaries today and I still see this - 

```
C:\Users\anmishr\Downloads\dotnet-dev-win-x64.latest (2)> .\dotnet.exe restore --help

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 3759 ms
Expanding 100% 16574 ms
.NET dependency restorer

Usage: restore [arguments] [options] [args]

Arguments:
  [PROJECT]  Optional path to a project file or MSBuild arguments.

Options:
  -h|--help                          Show help information
  -s|--source <SOURCE>               Specifies a NuGet package source to use during the restore.
  -r|--runtime <RUNTIME_IDENTIFIER>  Target runtime to restore packages for.
  --packages <PACKAGES_DIRECTORY>    Directory to install packages in.
  --disable-parallel                 Disables restoring multiple projects in parallel.
  --configfile <FILE>                The NuGet configuration file to use.
  --no-cache                         Do not cache packages and http requests.
  --ignore-failed-sources            Treat package source failures as warnings.
  --no-dependencies                  Set this flag to ignore project to project references and only restore the root project
  -v|--verbosity                     Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]

Additional Arguments:
 Any extra options that should be passed to MSBuild. See 'dotnet msbuild -h' for available options.

```
```
C:\Users\anmishr\Downloads\dotnet-dev-win-x64.latest (2)> .\dotnet.exe pack --help
.NET Core NuGet Package Packer

Usage: pack [arguments] [options] [args]

Arguments:
  <PROJECT>  The project to pack, defaults to the project file in the current directory. Can be a path to any project file

Options:
  -h|--help                           Show help information
  -o|--output <OUTPUT_DIR>            Directory in which to place built packages.
  --no-build                          Skip building the project prior to packing. By default, the project will be built.
  --include-symbols                   Include packages with symbols in addition to regular packages in output directory.
  --include-source                    Include PDBs and source files. Source files go into the src folder in the resulting nuget package
  -c|--configuration <CONFIGURATION>  Configuration to use for building the project.  Default for most projects is  "Debug".
  --version-suffix <VERSION_SUFFIX>   Defines the value for the $(VersionSuffix) property in the project.
  -s|--serviceable                    Set the serviceable flag in the package. For more information, please see https://aka.ms/nupkgservicing.
  -v|--verbosity                      Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]

Additional Arguments:
 Any extra options that should be passed to MSBuild. See 'dotnet msbuild -h' for available options.

```
```
C:\Users\anmishr\Downloads\dotnet-dev-win-x64.latest (2)> .\dotnet.exe --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\anmishr\Downloads\dotnet-dev-win-x64.latest (2)\sdk\1.0.0-rc4-004771
```

Am I missing something here?

**Comment by piotrpMSFT** [comment]
@jonsequitur can you take a look?

**Comment by mishra14** [comment]
Verified fixed in - 

```
E:\NuGet.Client [dev-anmishr-warning ≡]> dotnetlocal --info
.NET Command Line Tools (2.0.0-preview2-005910)

Product Information:
 Version:            2.0.0-preview2-005910
 Commit SHA-1 hash:  f3a4b22457

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   E:\cli\artifacts\win10-x64\stage2\sdk\2.0.0-preview2-005910

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002093-00
  Build    : 1a195046fd92bd73d993d804bea2f4506c2b56f1
```
