### ISSUE TITLE
VS 2017 RC  error: Cannot find project info for... This can indicate a missing project reference

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/cli#5144]
## Steps to reproduce
1. Create ASP.Core project (.NET Framework), then update to latest Nuget packages;
2. Create Class Library 1 (.NET Framework), add Microsoft.EntityFrameworkCore.SqlServer nuget package
3. Create Class Library 2 (.NET Framework), add Microsoft.EntityFrameworkCore.Relational nuget package
4. Compile to test: solution should be possible to compile
5. Create References: 
    add project reference "Library 1" to "Library 2" 
    add project reference "Library 2" to ASP.Core
6. Compile

## Expected  behavior
Compiled solution. Or compilation error message that contains useful information.

## Actual behavior
Compilation error

![image](https://cloud.githubusercontent.com/assets/11598038/21461233/61914c70-c958-11e6-9e1f-1eb2dc2039b0.png)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

## Solution: 
[WebApplication2.zip](https://github.com/dotnet/cli/files/671381/WebApplication2.zip)

**Comment by ByronAP** [comment]
same issue here with a .net standard class library

**Comment by xiexin36** [comment]
I have the same problem

**Comment by NickCraver** [comment]
Also hitting this in my ASP.NET Core samples, unsure of the cause yet.

**Comment by NickCraver** [comment]
Okay so the issue is that transitive dependencies do not work. If Project A references Project B, then Project A must (at the moment) **directly** reference the projects referenced in Project B. 

For example: if `A` references `B` and `B` references `C`, to get rid of this error `A` must reference `B` and `C` directly.

**Comment by z-ji** [comment]
same issue here.

**Comment by BizzyIzDizzy** [comment]
Same issue - Is this behaviour intentional?

**Comment by piotrpMSFT** [comment]
@dsplaisted I believe this is fixed in most recent SDK. Can you confirm?

**Comment by BizzyIzDizzy** [comment]
@piotrpMSFT I couldn't reproduce this behaviour with one of the latest builds:

λ dotnet --info
.NET Command Line Tools (1.0.0-rc4-004598)

Product Information:
 Version:            1.0.0-rc4-004598
 Commit SHA-1 hash:  1dfee9ead8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004598

**Comment by mgwalm** [comment]
The problem still occurs today using VS2017 RC 26020.
However it is not always possible to do as suggested because it could add cycles of references.

**Comment by BizzyIzDizzy** [comment]
@mgwalm I don't think this is a problem with the latest sdk rc4 but with the visual studio plugin - I have been finding a lot of differences between building from command line using dotnet build and building through visual studio 2017 rc. I believe the plugin is not up to date or VS is doing something "smart".

**Comment by mgwalm** [comment]
Do MS know this?

**Comment by piotrpMSFT** [comment]
@mgwalm can you install the latest VS RC? as @BizzyIzDizzy pointed out, this is not repro'ing in recent CLI builds, including the RC3 build that went out in the latest Visual Studio RC. If you see this atop the latest VS, please let us know!

**Comment by lyminhquanoutlookcom** [comment]
I have the same problem, but in MacOS with VS for Mac, open solution in VS 2017 in Windows is okay. So boring, I dreamed about one day I can code dotnetcore in my Mac :(

**Comment by bkapo** [comment]
i have the same problem in MacOS (preview 3)

**Comment by piotrpMSFT** [comment]
@bkapo that's a fairly old CLI build. Can you install RC4 from the home page of this repo and, if you're still seeing an issue, can you open a new one? If there is a problem in VS for Mac then the investigation will be fairly independent of this issue.

**Comment by mgwalm** [comment]
Ive got RC.3+26127.3 and the problem seems to have been resolved.

**Comment by piotrpMSFT** [comment]
Thanks @mgwalm. That's what I see as well.

**Comment by bkapo** [comment]
I have the same problem with RC4. 
I am using VS for Mac ... 

.NET Command Line Tools (1.0.0-rc4-004767)
Product Information:
 Version:            1.0.0-rc4-004767
 Commit SHA-1 hash:  f7978d90e6
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004767

**Comment by piotrpMSFT** [comment]
> If there is a problem in VS for Mac then the investigation will be fairly independent of this issue.

**Comment by clearbucketLabs** [comment]
Same here on a mac (though probably not really related to the os).

 How i fixed it was to delete all the obj and bin folders manually and restore the packages with CLI.(restore failed in VS for mac, "object not set to an instance..." but command line was fine).  Then rebuilt and it worked.   this is on the latest .net core tools, standard library etc... on a multi-project solution.

**Comment by ericwj** [comment]
I'm on Windows 10. VS 26206.0. I'm getting this from the command line too. `dotnet --version 1.0.0-rc4-004771`.

I had some success deleting `bin` and `obj` too, but remained stuck with non-transitive errors. The CLI and the VS Editor were complaing about identifiers I defined that are right there. Closing and reopening files would help, or reloading the solution. At least until I added another package dependency or a new code file. The depenency tree for the proejct couldn't open level 3 nodes (i.e. show transitive dependencies). I've seen build errors for transitive dependencies too. VS stops building complaining about a "" path. Some MSB3277 about `Microsoft.Extensions.DependencyModel`. Etc

**Comment by yielder** [comment]
Same issue here with  `Windows 10. VS 26206.0.   dotnet --version 1.0.0-rc4-004771`
Steps to reproduce:
1. Existing Console App 1 (.NET Framework).
2. Create ASP.Core project (.NET Framework)
3. Create References:
add project reference ASP.Core to Console App 1
4. Install a nuget package for ASP.Core
5 Compile

**Comment by FrancoisM** [comment]
Same here. First attempt at using .Net Standard libraries...
Windows 10 and Visual Studio 15.0.0-RC.4+26206.0

**Comment by StenPetrov** [comment]
This issue is marked closed but I'm seeing it with the released VS 2017, how do I fix it?
I tried adding all the references to my .NET Core project still no luck

**Comment by CornedBee** [comment]
Also had this in a TFS build using Visual Studio solution task set to use VS2017 RTM. Making the transitive project references direct solved it, but seems suboptimal.

**Comment by munyirik** [comment]
Seeing this problem with released VS 2017 as well.

**Comment by livarcocc** [comment]
Can you share a repro of this issue? Does restoring/building through the command line work?

**Comment by munyirik** [comment]
Found out what I was doing wrong. I was thrown off by the error message...

>> Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot find project info for ... This can indicate a missing project reference...

My problem was that I was targeting net452 in the class library I was referencing in a asp.net core app targeting netcoreapp1.1. I'd expect a 'mismatch' error instead.

**Comment by livarcocc** [comment]
Please, file an issue for the better error message at dotnet/sdk repo.

**Comment by cwoodruff** [comment]
I am getting it in VS 2017 version 15.1 (26403.0) Release. The difference I see is that the reference is broken is 2 level separation. All my other working references are only 1 level separation.

`  <ItemGroup>
    <ProjectReference Include="..\..\Chinook.API\Chinook.API.csproj" />
  </ItemGroup>`

Cannot find project info for 'C:\Git\ProjectChinook\src\API\Chinook.Domain\Chinook.Domain.csproj'. This can indicate a missing project reference.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets	92

**Comment by ch-hristov** [comment]
I just got this today, is it moved to another issue or?

**Comment by rkosafo** [comment]
Just had this issue as well. No `net452` class library. All apps were .net core only. Trying to reference all transient libraries did not work. Any work around?

**Comment by Slaters** [comment]
I've fixed this problem just setting the project with this issue to the same target framework that the refference project. My main project was on the framework 4.5.2 and the refference project was on 4.6.2. To change the framework of your project just go to: properties >> Application >> Target Framework

**Comment by clearbucketLabs** [comment]
@Slaters I got the issue with no such mismatch, .net core not 4.x versions.   either error message is misleading or it's something else.  surprised this  shipped with vs 2017... impossible to do serious work when you spend 90% of your project trying to figure out these  vague errors for common project setups.

**Comment by EliiseS** [comment]
I had this problem. Command: donet restore fixed this.

**Comment by flipchart** [comment]
I had the same error. It was caused by an invalid hint path that VS added with one of the quick actions. Delete the hint path and all good again

**Comment by jhudsoncedaron** [comment]
1) Running dotnet restore is mandatory or it won't work. VS's "restoring packages" somehow doesn't make it work.
2) The error message is pretty useless. It doesn't even flag the right project but always the last no-link project on the list.

**Comment by HelloKitty** [comment]
If you guys changed the dependencies' target standard, like from netstandard1.5 to netstandard1.0, you will have to remove the hintpath in the target project's .csproj.

For example ```<HintPath>..\FreecraftCore.Serializer.Metadata\bin\Debug\netstandard1.5\FreecraftCore.Serializer.Metadata.dll</HintPath>```

Hints to netstandard1.5 directory so we need to remove the hint path manually by opening up the .csproj file and removing it.

**Comment by jhudsoncedaron** [comment]
@HelloKitty : The case I found had zilch-all to do with HintPath; there was no HintPath in the .csproj file.

**Comment by atanasa** [comment]
I am hitting this with a directly referenced project and no HintPath. I am running VS 2017 (15.2)

Project A is for netstandard1.0
Project B is for netstandard2.0 and net45
Project B references project A

Doing a manual `dotnet restore` seems to fix it.

**Comment by alittleteap0t** [comment]
@HelloKitty Thanks for the help.  I did switch my .NET Core version, and had endless frustration until I read your comment.

**Comment by Allann** [comment]
I am seeing same error in VSTS builds, works fine in vs2017 15.2 (26430.16).  Even if I build the code retrieved directly by the build agent in VS it works fine.  Extract from build log below:

> 2017-07-18T22:19:45.9363559Z _TransformWebConfig:
> 2017-07-18T22:19:45.9363559Z   Updating web.config at 'D:\agent\_work\3\s\Dev\Jbssa.MasterData\src\Jbssa.MasterData.Web\obj\Release\netcoreapp1.1\PubTmp\Out\web.config'
> 2017-07-18T22:19:45.9988579Z ##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeployPackage.targets(124,7): Error MSB4184: The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.
> 2017-07-18T22:19:45.9988579Z ##[debug]Processed: ##vso[task.logissue type=Error;sourcepath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeployPackage.targets;linenumber=124;columnnumber=7;code=MSB4184;]The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.
> 2017-07-18T22:19:45.9988579Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeployPackage.targets(124,7): error MSB4184: The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form. [D:\agent\_work\3\s\Dev\Jbssa.MasterData\src\Jbssa.MasterData.Web\Jbssa.MasterData.Web.csproj]
> 2017-07-18T22:19:45.9988579Z ##[debug]Processed: ##vso[task.logdetail id=684ee0b4-95e9-4006-9e71-2878c4d45827;parentid=bb44fdf5-ab76-4f98-b9c0-ee7786811479;type=Build;result=Failed;finishtime=2017-07-18T22:19:45.9988579Z;progress=100;state=Completed;parentid=bb44fdf5-ab76-4f98-b9c0-ee7786811479;name=;]
> 2017-07-18T22:19:45.9988579Z Done Building Project "D:\agent\_work\3\s\Dev\Jbssa.MasterData\src\Jbssa.MasterData.Web\Jbssa.MasterData.Web.csproj" (default targets) -- FAILED.
>

**Comment by sturlath** [comment]
This [answer on StackOverflow](https://stackoverflow.com/a/42658357/1187583) got me to just update all my projects from .net 4.5.2 to .net 4.6.1 and now this error is gone. Hope this info helps somebody.

**Comment by Allann** [comment]
This appears to be a "generic error" that they spit out.  It turned out to be an error in the default values the msbuild task added in the build definition.  I changed the MSBuild Arguments to this:

> /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"


and all was good again.  I don't think adding a new target framework is a good idea in many circumstances.  Your applications should be targeting specific frameworks for a reason I assume.

**Comment by se7vanj** [comment]
On a similar problem with my machine, I had to reset the below file which was accidentally modified when I was trying to make my assemblies to be on net45 and core api targetting to net45. After that it was not building my solution and started to throw different errors, even after I reverted back everything to target with .net core. Tried deleting VS related cache/settings folders of my local user login, no result, then I was about to uninstall VS2017, before that found the below file had a modified timestamp and somehow got its original content. Now its fine to build and run my original solution which is targetting to .net core.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets

**Comment by WolfyUK** [comment]
For me, this was a case sensitivity issue. The folder containing the dependent project had been renamed and the consuming project file updated, but the solution file had not. Making sure all paths match correctly in `.sln`, `.csproj` and physically on disk resolved the `Cannot find project info` issue.

**Comment by MovGP0** [comment]
I had to delete the `.FileListAbsolute.txt` and `nuget.g.targets` files to make the build work for me: 

```powershell
Get-ChildItem . -Recurse -Force | where { $_.Name -match ".*FileListAbsolute.txt" } | Remove-Item
Get-ChildItem . -Recurse -Force | where { $_.Name -match ".*nuget.g.targets" } | Remove-Item
```

**Comment by Mo2men20** [comment]
I restarted VS and it worked fine.

**Comment by sysaxis** [comment]
Open /obj/project.assets and remove the project from the targets. Worked for me. For some reason the project.assets contains even the referenced projects from excluded files.

**Comment by Citizen39** [comment]
Thank you @WolfyUK ! Same scenario for me, and your tip resolved my similar issue. Cheers!

**Comment by michaelthyregod** [comment]
I can confirm that it seems to be the casing of the path that needs to be exactly as it is in the filesystem. This goes for the Include in <ProjectReference Include=""/> in *.csproj files and for any project path reference in the sln file.
Might be a good idea to implement a proper comparer for comparing the path, and not rely on casing.

**Comment by sivakspt** [comment]
I have unloaded the project and reloaded the project it work from me.

**Comment by mikebridge** [comment]
Deleting `obj` and `bin` and restoring worked for me as per @clearbucketLabs.

**Comment by vtkhanh** [comment]
dotnet restore works for me. oops...

**Comment by GHR-Arash** [comment]
> Okay so the issue is that transitive dependencies do not work. If Project A references Project B, then Project A must (at the moment) **directly** reference the projects referenced in Project B.
> 
> For example: if `A` references `B` and `B` references `C`, to get rid of this error `A` must reference `B` and `C` directly.

This is Not Correct Behavior , so what id then Project C reference project D and Project D Reference Project E and ....
should i add dependency graph manually ?
