### ISSUE TITLE
Publish to ubuntu.16.04-arm causes files to not be found when running

### ISSUE THREAD

**Issue by 165plo** [dotnet/cli#6566]
## Links
This is a recreation of [issue 6510](https://github.com/dotnet/cli/issues/6510) as the recommendations did not solve the issue.

## Steps to reproduce
Following the guide below I was able to run a dotnet core app on my Raspberry Pi
https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md
by @Petermarcu
I also took a look at https://timdows.com/projects/asp-net-core-2-0-0-beta-on-a-raspberry-pi-3/#run-mvc
I am also running this in a docker container, but the guide above ran no problem.

Run:
dotnet new mvc
dotnet restore
dotnet publish -r ubuntu.16.04-arm
Copy publish folder to Raspberry Pi
Attempt to run the published files 
     Run chmod u+x executableFile
     ./executableFile

## Expected  behavior
There server starts up correctly.

## Actual behavior
Error: assembly specified in the dependencies manifest was not found -- package: 'Microsoft.AspNetCore.Antiforgery', version: '2.0.0-preview1-24647', path: 'lib/netstandard1.3/Microsoft.AspNetCore.Antiforgery.dll'

## Environment data
dotnet --info output:
.NET Command Line Tools (2.0.0-preview2-005905)

Product Information:
Version: 2.0.0-preview2-005905
Commit SHA-1 hash: 2cc5612

Runtime Environment:
OS Name: ubuntu
OS Version: 16.04
OS Platform: Linux
RID: ubuntu.16.04-x64
Base Path: /home/david/Documents/DotNet2.0Preview/sdk/2.0.0-preview2-005905

Microsoft .NET Core Shared Framework Host

Version : 2.0.0-preview2-002093-00
Build : 1a195046fd92bd73d993d804bea2f4506c2b56f1

I also tried using preview1 as suggested in the previous example

a.csproj:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifiers>win8-arm;ubuntu.14.04-arm;ubuntu.16.04-arm</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-24647" />
    <!-- PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.0-preview1-24647" / -->
  </ItemGroup>

  <!-- ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview1-24647" />
  </ItemGroup -->

</Project>

```

**Comment by livarcocc** [comment]
This is an issue that we have fixed in preview1 already. Can you try getting a build from release/2.0.0? We have actually ported it over to preview2 as well but we have been having build issues with it, which is why you are still hitting this.

**Comment by 165plo** [comment]
@livarcocc As mentioned in the Environment Data section above. I tried using preview1 from the release/2.0.0 branch and was still experiencing the same issue. Is there something about how the publish folder needs to be deployed that would change where it is looking? As mentioned I do not have the lib/netstandard1.3 that dotnet is looking in to find the dlls. Or is there a specific install that needs to be run on my ARM machine to get that folder?

**Comment by 165plo** [comment]
How do I reopen closed issues?
