### ISSUE TITLE
No diagnostic information when resolving a command with .NET Core SDK 2.0

### ISSUE THREAD

**Issue by mrward** [dotnet/cli#7486]
## Steps to reproduce

Try to see diagnostic information when a command is being resolved.

 - dotnet -d unknowncommand

Or:

  - dotnet --diagnostics unknowncommand

## Expected  behavior

Similar behaviour to NET Core SDK 1.0.4 where you see output on how the command is being resolved:

```
Telemetry is: Disabled
projectfactory: MSBUILD_EXE_PATH = /usr/local/share/dotnet/sdk/1.0.4/MSBuild.dll
projectfactory: MSBuild project path = ~/Projects/Tests/TestProject/TestProject.csproj
projecttoolscommandresolver: resolving commandspec from 2 Tool Libraries.
projecttoolscommandresolver: Attempting to resolve command spec from tool Microsoft.VisualStudio.Web.CodeGeneration.Tools
projecttoolscommandresolver: nuget packages root:
- ~/.nuget/packages/
- ~/.dotnet/NuGetFallbackFolder
projecttoolscommandresolver: found tool lockfile at : ~/.nuget/packages/.tools/microsoft.visualstudio.web.codegeneration.tools/1.0.1/netcoreapp1.0/project.assets.json
projecttoolscommandresolver: expect deps.json at: ~/.nuget/packages/.tools/microsoft.visualstudio.web.codegeneration.tools/1.0.1/netcoreapp1.0/Microsoft.VisualStudio.Web.CodeGeneration.Tools.deps.json
projecttoolscommandresolver: attempting to create commandspec
packagedcommandspecfactory: attempting to find command dotnet-unknowncommand in Microsoft.VisualStudio.Web.CodeGeneration.Tools
packagedcommandspecfactory: failed to find toolAssembly for dotnet-unknowncommand
projecttoolscommandresolver: commandSpec is null.
projecttoolscommandresolver: Attempting to resolve command spec from tool BundlerMinifier.Core
projecttoolscommandresolver: nuget packages root:
- ~/.nuget/packages/
- ~/.dotnet/NuGetFallbackFolder
projecttoolscommandresolver: found tool lockfile at : ~/.nuget/packages/.tools/bundlerminifier.core/2.4.337/netcoreapp1.0/project.assets.json
projecttoolscommandresolver: expect deps.json at: ~/.nuget/packages/.tools/bundlerminifier.core/2.4.337/netcoreapp1.0/BundlerMinifier.Core.deps.json
projecttoolscommandresolver: attempting to create commandspec
packagedcommandspecfactory: attempting to find command dotnet-unknowncommand in BundlerMinifier.Core
packagedcommandspecfactory: failed to find toolAssembly for dotnet-unknowncommand
projecttoolscommandresolver: commandSpec is null.
projecttoolscommandresolver: failed to resolve commandspec from library.
Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-unknowncommand"
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Actual behavior

No diagnostic output is shown for resolving the command.

```
Telemetry is: Disabled
No executable found matching command "dotnet-unknowncommand"
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by peterhuene** [comment]
This may have been fixed with https://github.com/dotnet/cli/commit/e0e39d044dee8c519e269b66a69bc298276decf2. It appears that the `--diagnostics` switch was not properly setting verbose logging on, preventing the expected output.

**Comment by livarcocc** [comment]
Hum, even in master I still don't see the verbose messages when doing tool resolution that I expected to see, so there is something still going on there.

**Comment by peterhuene** [comment]
I also do not see the exact same diagnostic information, but I'm ignorant of whether or not that is a result of running `dotnet` from the build location and not from an install. 

For example, the `nuget packages root` message does not get printed because `MSBuildProject.GetTools` returns an empty collection for me in the `ProjectToolsCommandResolver`.

**Comment by livarcocc** [comment]
I tried it in a project with a tool, so I should have seen the whole diagnostics poping out, but I got nothing. Passing -d should give you diagnostics for a installed CLI or a CLI that you built locally.

**Comment by peterhuene** [comment]
2.0.0:
```
$ dotnet -d unknowncommand
Telemetry is: Enabled
No executable found matching command "dotnet-unknowncommand"
```

master:
```
$ /Users/peterhuene/src/cli/bin/2/osx.10.13-x64/dotnet/dotnet -d unknowncommand
Telemetry is: Enabled
projectfactory: MSBUILD_EXE_PATH = /Users/peterhuene/src/cli/bin/2/osx.10.13-x64/dotnet/sdk/2.1.0-preview1-007365/MSBuild.dll
projectfactory: MSBuild project path = /Users/peterhuene/foo/foo.csproj
projecttoolscommandresolver: resolving commandspec from 0 Tool Libraries.
projecttoolscommandresolver: failed to resolve commandspec from library.
Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-unknowncommand"
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

I assume that had the project had tools (still a little ignorant with the design here), additional diagnostic logging would have occurred.

**Comment by livarcocc** [comment]
You are right. I figure out why I didn't see it. I built the CLI but then forgot to update my path and still had 2.0.0 in it. I am closing this issue. Thank you for taking a look.
