### ISSUE TITLE
'dotnet new xunit/mstest' commands always write to stderr

### ISSUE THREAD

**Issue by bergmeister** [dotnet/cli#7888]
## Steps to reproduce
Executing `dotnet new mstest` or `dotnet new xunit` writes to stderr when being executed in `PowerShell 5.1`. This means that one sees red herring errors in CI systems like `AppVeyor` where stderr is treated as an error, see for example the original issue [here](https://github.com/appveyor/ci/issues/1873).
```powershell
dotnet new xunit 2>stderr.txt # capture stderr in file
cat .\stderr.txt
```
## Expected  behavior
The file should be empty if the command was successful.
## Actual behavior
The following was written to stderr
```
At line:1 char:1
+ & dotnet new xunit  2>stderr2.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by livarcocc** [comment]
@mlorbetske @seancpeters  can you take a look?

**Comment by mlorbetske** [comment]
If all that's getting written to stderr is whitespace, a fix has been made for that for the 2.1 wave https://github.com/dotnet/templating/pull/1291

**Comment by livarcocc** [comment]
Closing as this has been fixed in master.

**Comment by bergmeister** [comment]
@livarcocc @mlorbetske  : I have installed the latest daily build from your GitHub page [here](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe) and I still get whitespace written to stderr. In addition, the dotnet new commands for xunit and mstest also seem to be broken:
```powershell
PS C:\Users\chris\test> dotnet --info
.NET Command Line Tools (2.2.0-preview1-007460)

Product Information:
 Version:            2.2.0-preview1-007460
 Commit SHA-1 hash:  173cc035e4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.0-preview1-007460\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25825-07
  Build    : 4c165c13bd390adf66f9af30a088d634d3f37a9d

PS C:\Users\chris\test> dotnet new xunit 2> stderr.txt
The template "xUnit Test Project" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Users\chris\test\test.csproj...
  Restoring packages for C:\Users\chris\test\test.csproj...
C:\Users\chris\test\test.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.1.0-prev
iew1-25825-07)
C:\Users\chris\test\test.csproj : error NU1102:   - Found 16 version(s) in nuget.org [ Nearest version: 2.0.0 ]
  Generating MSBuild file C:\Users\chris\test\obj\test.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\chris\test\obj\test.csproj.nuget.g.targets.
  Restore failed in 3.79 sec for C:\Users\chris\test\test.csproj.

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

PS C:\Users\chris\test> cat .\stderr.txt
dotnet :
At line:1 char:1
+ dotnet new xunit 2> serr.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
````
